<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.CarrierEntry</code>
 */
class CarrierEntry extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     */
    protected $carrier_code = '';
    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     */
    protected $channel = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrier_code
     *     @type string $channel
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrier_code;
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @return string
     */
    public function getChannel()
    {
        return $this->channel;
    }

    /**
     * Generated from protobuf field <code>string channel = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setChannel($var)
    {
        GPBUtil::checkString($var, True);
        $this->channel = $var;

        return $this;
    }

}

