<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.DetectRequest</code>
 */
class DetectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string tracking_no = 1;</code>
     */
    protected $tracking_no = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $tracking_no
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 1;</code>
     * @return string
     */
    public function getTrackingNo()
    {
        return $this->tracking_no;
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_no = $var;

        return $this;
    }

}

