<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.QueryRequest</code>
 */
class QueryRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     */
    protected $carrier_code = '';
    /**
     * Generated from protobuf field <code>string tracking_no = 2;</code>
     */
    protected $tracking_no = '';
    /**
     * 多凭证场景指定 credential_id（空串 = 使用承运商默认凭证）
     *
     * Generated from protobuf field <code>string credential_id = 3;</code>
     */
    protected $credential_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrier_code
     *     @type string $tracking_no
     *     @type string $credential_id
     *           多凭证场景指定 credential_id（空串 = 使用承运商默认凭证）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrier_code;
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 2;</code>
     * @return string
     */
    public function getTrackingNo()
    {
        return $this->tracking_no;
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_no = $var;

        return $this;
    }

    /**
     * 多凭证场景指定 credential_id（空串 = 使用承运商默认凭证）
     *
     * Generated from protobuf field <code>string credential_id = 3;</code>
     * @return string
     */
    public function getCredentialId()
    {
        return $this->credential_id;
    }

    /**
     * 多凭证场景指定 credential_id（空串 = 使用承运商默认凭证）
     *
     * Generated from protobuf field <code>string credential_id = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setCredentialId($var)
    {
        GPBUtil::checkString($var, True);
        $this->credential_id = $var;

        return $this;
    }

}

