<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.QueryResponse</code>
 */
class QueryResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 0 成功；400/404 参数与未注册；5001 carrier_error；500 内部错误（与对外契约一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * Generated from protobuf field <code>string error_code = 3;</code>
     */
    protected $error_code = '';
    /**
     * Generated from protobuf field <code>string error_message = 4;</code>
     */
    protected $error_message = '';
    /**
     * Generated from protobuf field <code>string query_no = 5;</code>
     */
    protected $query_no = '';
    /**
     * Generated from protobuf field <code>string carrier_code = 6;</code>
     */
    protected $carrier_code = '';
    /**
     * Generated from protobuf field <code>string tracking_no = 7;</code>
     */
    protected $tracking_no = '';
    /**
     * TrackStatus 统一状态值（pending/in_transit/out_for_delivery/delivered/exception/returned/unknown）
     *
     * Generated from protobuf field <code>string status = 8;</code>
     */
    protected $status = '';
    /**
     * Generated from protobuf field <code>string delivered_at = 9;</code>
     */
    protected $delivered_at = '';
    /**
     * Generated from protobuf field <code>string estimated_delivery_at = 10;</code>
     */
    protected $estimated_delivery_at = '';
    /**
     * Generated from protobuf field <code>string latest_description = 11;</code>
     */
    protected $latest_description = '';
    /**
     * Generated from protobuf field <code>string raw_status = 12;</code>
     */
    protected $raw_status = '';
    /**
     * Generated from protobuf field <code>repeated .internal.v1.TrackingEvent events = 13;</code>
     */
    private $events;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           0 成功；400/404 参数与未注册；5001 carrier_error；500 内部错误（与对外契约一致）
     *     @type string $message
     *     @type string $error_code
     *     @type string $error_message
     *     @type string $query_no
     *     @type string $carrier_code
     *     @type string $tracking_no
     *     @type string $status
     *           TrackStatus 统一状态值（pending/in_transit/out_for_delivery/delivered/exception/returned/unknown）
     *     @type string $delivered_at
     *     @type string $estimated_delivery_at
     *     @type string $latest_description
     *     @type string $raw_status
     *     @type array<\Internal\Grpc\TrackingEvent>|\Google\Protobuf\Internal\RepeatedField $events
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * 0 成功；400/404 参数与未注册；5001 carrier_error；500 内部错误（与对外契约一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 0 成功；400/404 参数与未注册；5001 carrier_error；500 内部错误（与对外契约一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_code = 3;</code>
     * @return string
     */
    public function getErrorCode()
    {
        return $this->error_code;
    }

    /**
     * Generated from protobuf field <code>string error_code = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string error_message = 4;</code>
     * @return string
     */
    public function getErrorMessage()
    {
        return $this->error_message;
    }

    /**
     * Generated from protobuf field <code>string error_message = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setErrorMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->error_message = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string query_no = 5;</code>
     * @return string
     */
    public function getQueryNo()
    {
        return $this->query_no;
    }

    /**
     * Generated from protobuf field <code>string query_no = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setQueryNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->query_no = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 6;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrier_code;
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 7;</code>
     * @return string
     */
    public function getTrackingNo()
    {
        return $this->tracking_no;
    }

    /**
     * Generated from protobuf field <code>string tracking_no = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTrackingNo($var)
    {
        GPBUtil::checkString($var, True);
        $this->tracking_no = $var;

        return $this;
    }

    /**
     * TrackStatus 统一状态值（pending/in_transit/out_for_delivery/delivered/exception/returned/unknown）
     *
     * Generated from protobuf field <code>string status = 8;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * TrackStatus 统一状态值（pending/in_transit/out_for_delivery/delivered/exception/returned/unknown）
     *
     * Generated from protobuf field <code>string status = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string delivered_at = 9;</code>
     * @return string
     */
    public function getDeliveredAt()
    {
        return $this->delivered_at;
    }

    /**
     * Generated from protobuf field <code>string delivered_at = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDeliveredAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->delivered_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string estimated_delivery_at = 10;</code>
     * @return string
     */
    public function getEstimatedDeliveryAt()
    {
        return $this->estimated_delivery_at;
    }

    /**
     * Generated from protobuf field <code>string estimated_delivery_at = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setEstimatedDeliveryAt($var)
    {
        GPBUtil::checkString($var, True);
        $this->estimated_delivery_at = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string latest_description = 11;</code>
     * @return string
     */
    public function getLatestDescription()
    {
        return $this->latest_description;
    }

    /**
     * Generated from protobuf field <code>string latest_description = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setLatestDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->latest_description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string raw_status = 12;</code>
     * @return string
     */
    public function getRawStatus()
    {
        return $this->raw_status;
    }

    /**
     * Generated from protobuf field <code>string raw_status = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setRawStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->raw_status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .internal.v1.TrackingEvent events = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEvents()
    {
        return $this->events;
    }

    /**
     * Generated from protobuf field <code>repeated .internal.v1.TrackingEvent events = 13;</code>
     * @param array<\Internal\Grpc\TrackingEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Internal\Grpc\TrackingEvent::class);
        $this->events = $arr;

        return $this;
    }

}

