<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.SubscribeResponse</code>
 */
class SubscribeResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * 0 成功；其余为业务错误（与 QueryResponse 语义一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    protected $code = 0;
    /**
     * Generated from protobuf field <code>string message = 2;</code>
     */
    protected $message = '';
    /**
     * 订阅 ID 与回调验签密钥（code==0 时返回，HMAC 验签用）
     *
     * Generated from protobuf field <code>int64 subscription_id = 3;</code>
     */
    protected $subscription_id = 0;
    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     */
    protected $secret = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $code
     *           0 成功；其余为业务错误（与 QueryResponse 语义一致）
     *     @type string $message
     *     @type int|string $subscription_id
     *           订阅 ID 与回调验签密钥（code==0 时返回，HMAC 验签用）
     *     @type string $secret
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * 0 成功；其余为业务错误（与 QueryResponse 语义一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     * 0 成功；其余为业务错误（与 QueryResponse 语义一致）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * 订阅 ID 与回调验签密钥（code==0 时返回，HMAC 验签用）
     *
     * Generated from protobuf field <code>int64 subscription_id = 3;</code>
     * @return int|string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * 订阅 ID 与回调验签密钥（code==0 时返回，HMAC 验签用）
     *
     * Generated from protobuf field <code>int64 subscription_id = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkInt64($var);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     * @return string
     */
    public function getSecret()
    {
        return $this->secret;
    }

    /**
     * Generated from protobuf field <code>string secret = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setSecret($var)
    {
        GPBUtil::checkString($var, True);
        $this->secret = $var;

        return $this;
    }

}

