<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: internal.proto

namespace Internal\Grpc;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>internal.v1.SubscribeRequest</code>
 */
class SubscribeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     */
    protected $carrier_code = '';
    /**
     * Generated from protobuf field <code>string callback_url = 2;</code>
     */
    protected $callback_url = '';
    /**
     * 订阅事件类型（空串 = tracking.update）
     *
     * Generated from protobuf field <code>string event_type = 3;</code>
     */
    protected $event_type = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $carrier_code
     *     @type string $callback_url
     *     @type string $event_type
     *           订阅事件类型（空串 = tracking.update）
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Internal\Internal::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @return string
     */
    public function getCarrierCode()
    {
        return $this->carrier_code;
    }

    /**
     * Generated from protobuf field <code>string carrier_code = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCarrierCode($var)
    {
        GPBUtil::checkString($var, True);
        $this->carrier_code = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string callback_url = 2;</code>
     * @return string
     */
    public function getCallbackUrl()
    {
        return $this->callback_url;
    }

    /**
     * Generated from protobuf field <code>string callback_url = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setCallbackUrl($var)
    {
        GPBUtil::checkString($var, True);
        $this->callback_url = $var;

        return $this;
    }

    /**
     * 订阅事件类型（空串 = tracking.update）
     *
     * Generated from protobuf field <code>string event_type = 3;</code>
     * @return string
     */
    public function getEventType()
    {
        return $this->event_type;
    }

    /**
     * 订阅事件类型（空串 = tracking.update）
     *
     * Generated from protobuf field <code>string event_type = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setEventType($var)
    {
        GPBUtil::checkString($var, True);
        $this->event_type = $var;

        return $this;
    }

}

